buildscript {
    ext {
        compose_version = '1.6.8'
        compose_compiler_version = '1.5.14'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
